workdir: /exp/xzhang/sockeye-recipes3/egs/asha/space1/
rootdir: /exp/xzhang/sockeye-recipes3/
src: zh
trg: en
train_tok: /exp/xzhang/sockeye-recipes3/egs/ted/multitarget-ted/en-zh/tok/ted_train_en-zh.tok.clean
valid_tok: /exp/xzhang/sockeye-recipes3/egs/ted/multitarget-ted/en-zh/tok/ted_dev_en-zh.tok
bpe_symbols_src:
- 30000
- 10000
bpe_symbols_trg:
- 30000
encoder: transformer
decoder: transformer
num_layers:
- "4:2"
- "6:3"
- "2:2"
- "2:4"
transformer_model_size: [256, 512, 1024]
transformer_attention_heads: 8
transformer_feed_forward_num_hidden: [1024, 2048]
optimized_metric: perplexity
embed_dropout:
- ".0:.0"
label_smoothing: 0.1
batch_size: 4096
update_interval: 1
initial_learning_rate: [0.0002, 0.001, 0.002]
seed: 13
checkpoint_interval: 500
max_num_checkpoint_not_improved: 32
max_checkpoints: 1
keep_last_params: 1
decode_and_evaluate: -1
